### ISSUE TITLE
s7-200 read  v memory  

### ISSUE THREAD

**Issue by shizetao** [plcpeople/nodeS7#90]
i use DB1,X100 to read v100 

return
buffer.js:336
    throw new ERR_INVALID_OPT_VALUE.RangeError('size', size);
    ^
RangeError [ERR_INVALID_OPT_VALUE]: The value "NaN" is invalid for option "size"
    at Function.alloc (buffer.js:345:3)
    at processS7Packet (node_modules/nodes7/nodeS7.js:1626:33)
    at NodeS7.readResponse (/node_modules/nodes7/nodeS7.js:1372:17)
    at NodeS7.onResponse (/node_modules/nodes7/nodeS7.js:1237:9)
    at Socket.<anonymous> (/node_modules/nodes7/nodeS7.js:407:20)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  code: 'ERR_INVALID_OPT_VALUE'
}

where am i wrong

**Comment by shizetao** [comment]
i set wrong ip  ...... my bad
